const DataApi=[
    { "id": 1,
      "category": "electronics", 
      "name": "Portable Charger", 
      "image": "https://example.com/images/electronics1.jpg", 
      "price": 19.99, 
      "rating": 4.8 
    },
    { "id": 2,
      "category": "electronics", 
      "name": "Wireless Earbuds", 
      "image": "https://example.com/images/electronics2.jpg", 
      "price": 39.99, 
      "rating": 4.6 
    },
    { "id": 3,
      "category": "electronics", 
      "name": "Bluetooth Speaker", 
      "image": "https://example.com/images/electronics3.jpg", 
      "price": 29.99, 
      "rating": 4.5 
    },
    { "id": 4,
      "category": "electronics", 
      "name": "Smart Watch", 
      "image": "https://example.com/images/electronics4.jpg", 
      "price": 69.99, 
      "rating": 4.4 
    },
    { "id": 5,
      "category": "electronics", 
      "name": "Webcam", 
      "image": "https://example.com/images/electronics5.jpg", 
      "price": 49.99, 
      "rating": 4.3 
    },
    { "id": 6,
      "category": "electronics", 
      "name": "USB-C Hub", 
      "image": "https://example.com/images/electronics6.jpg", 
      "price": 24.99, 
      "rating": 4.2 
    },
    { "id": 7,
      "category": "electronics", 
      "name": "LED Light Strip", 
      "image": "https://example.com/images/electronics7.jpg", 
      "price": 14.99, 
      "rating": 4.4 
    },
    { "id": 8,
      "category": "electronics", 
      "name": "VR Headset", 
      "image": "https://example.com/images/electronics8.jpg", 
      "price": 109.99, 
      "rating": 4.1 
    },
    { "id": 9,
      "category": "electronics", 
      "name": "Portable Projector", 
      "image": "https://example.com/images/electronics9.jpg", 
      "price": 199.99, 
      "rating": 4.3 
    },
    { "id": 10,
      "category": "electronics", 
      "name": "External SSD", 
      "image": "https://example.com/images/electronics10.jpg", 
      "price": 89.99, 
      "rating": 4.6 
    },

    { "id": 11,
      "category": "fashion", 
      "name": "Crew Neck T‑Shirt", 
      "image": "https://example.com/images/fashion1.jpg", 
      "price": 19.99, 
      "rating": 4.5 
    },
    { "id": 12,
      "category": "fashion", 
      "name": "Slim-fit Jeans", 
      "image": "https://example.com/images/fashion2.jpg", 
      "price": 49.99, 
      "rating": 4.4 
    },
    { "id": 13,
      "category": "fashion", 
      "name": "Canvas Sneakers", 
      "image": "https://example.com/images/fashion3.jpg", 
      "price": 59.99, 
      "rating": 4.6 
    },
    { "id": 14,
      "category": "fashion", 
      "name": "Leather Belt", 
      "image": "https://example.com/images/fashion4.jpg", 
      "price": 24.99, 
      "rating": 4.3 
    },
    { "id": 15,
      "category": "fashion", 
      "name": "Sunglasses (Aviator)", 
      "image": "https://example.com/images/fashion5.jpg", 
      "price": 29.99, 
      "rating": 4.4 
    },
    { "id": 16,
      "category": "fashion", 
      "name": "Wool Scarf", 
      "image": "https://example.com/images/fashion6.jpg", 
      "price": 22.99, 
      "rating": 4.2 
    },
    { "id": 17,
      "category": "fashion", 
      "name": "Denim Jacket", 
      "image": "https://example.com/images/fashion7.jpg", 
      "price": 79.99, 
      "rating": 4.5 
    },
    { "id": 18,
      "category": "fashion", 
      "name": "Chelsea Boots", 
      "image": "https://example.com/images/fashion8.jpg", 
      "price": 99.99, 
      "rating": 4.7 
    },
    { "id": 19,
      "category": "fashion", 
      "name": "Baseball Cap", 
      "image": "https://example.com/images/fashion9.jpg", 
      "price": 14.99, 
      "rating": 4.1 
    },
    { "id": 20,
      "category": "fashion", 
      "name": "Canvas Backpack", 
      "image": "https://example.com/images/fashion10.jpg", 
      "price": 44.99, 
      "rating": 4.6 
    },

    { "id": 21,
      "category": "home", 
      "name": "Air Fryer", 
      "image": "https://example.com/images/home1.jpg", 
      "price": 89.99, 
      "rating": 4.5 
    },
    { "id": 22,
      "category": "home", 
      "name": "Robot Vacuum", 
      "image": "https://example.com/images/home2.jpg", 
      "price": 249.99, 
      "rating": 4.3 
    },
    { "id": 23,
      "category": "home", 
      "name": "LED Table Lamp", 
      "image": "https://example.com/images/home3.jpg", 
      "price": 29.99, 
      "rating": 4.4 
    },
    { "id": 24,
      "category": "home", 
      "name": "Decorative Rug", 
      "image": "https://example.com/images/home4.jpg", 
      "price": 59.99, 
      "rating": 4.2 
    },
    { "id": 25,
      "category": "home", 
      "name": "Wall Art Print", 
      "image": "https://example.com/images/home5.jpg", 
      "price": 39.99, 
      "rating": 4.5 
    },
    { "id": 26,
      "category": "home", 
      "name": "Bookshelf", 
      "image": "https://example.com/images/home6.jpg", 
      "price": 129.99, 
      "rating": 4.3 
    },
    { "id": 27,
      "category": "home", 
      "name": "Dining Table (Wooden)", 
      "image": "https://example.com/images/home7.jpg", 
      "price": 299.99, 
      "rating": 4.6 
    },
    { "id": 28,
      "category": "home", 
      "name": "Curtain Panels", 
      "image": "https://example.com/images/home8.jpg", 
      "price": 49.99, 
      "rating": 4.1 
    },
    { "id": 29,
      "category": "home", 
      "name": "Floor Mirror", 
      "image": "https://example.com/images/home9.jpg", 
      "price": 89.99, 
      "rating": 4.4 
    },
    { "id": 30,
      "category": "home", 
      "name": "Storage Bins (Set of 3)", 
      "image": "https://example.com/images/home10.jpg", 
      "price": 34.99, 
      "rating": 4.2 
    },
    { "id": 31,
      "category": "books", 
      "name": "The Great Gatsby", 
      "image": "https://example.com/images/books1.jpg", 
      "price": 9.99, 
      "rating": 4.7 
    },
    { "id": 32,
      "category": "books", 
      "name": "1984 by George Orwell", 
      "image": "https://example.com/images/books2.jpg", 
      "price": 8.99, 
      "rating": 4.8 
    },
    { "id": 33,
      "category": "books", 
      "name": "To Kill a Mockingbird", 
      "image": "https://example.com/images/books3.jpg", 
      "price": 7.99, 
      "rating": 4.9 
    },
    { "id": 34,
      "category": "books", 
      "name": "The Hobbit", 
      "image": "https://example.com/images/books4.jpg", 
      "price": 10.99, 
      "rating": 4.8 
    },
    { "id": 35,
      "category": "books", 
      "name": "Sapiens: A Brief History of Humankind", 
      "image": "https://example.com/images/books5.jpg", 
      "price": 14.99, 
      "rating": 4.7 
    },
    { "id": 36,
      "category": "books", 
      "name": "The Catcher in the Rye", 
      "image": "https://example.com/images/books6.jpg", 
      "price": 9.49, 
      "rating": 4.2 
    },
    { "id": 37,
      "category": "books", 
      "name": "Harry Potter and the Sorcerer's Stone", 
      "image": "https://example.com/images/books7.jpg", 
      "price": 12.99, 
      "rating": 4.9 
    },
    { "id": 38,
      "category": "books", 
      "name": "Pride and Prejudice", 
      "image": "https://example.com/images/books8.jpg", 
      "price": 8.49, 
      "rating": 4.6 
    },
    { "id": 39,
      "category": "books", 
      "name": "Meditations by Marcus Aurelius", 
      "image": "https://example.com/images/books9.jpg", 
      "price": 6.99, 
      "rating": 4.8 
    },
    { "id": 40,
      "category": "books", 
      "name": "Atomic Habits", 
      "image": "https://example.com/images/books10.jpg", 
      "price": 11.99, 
      "rating": 4.7 
    },

    { "id": 41,
      "category": "fitness", 
      "name": "Yoga Mat", 
      "image": "https://example.com/images/fitness1.jpg", 
      "price": 19.99, 
      "rating": 4.8 
    },
    { "id": 42,
      "category": "fitness", 
      "name": "Dumbbell Set (10-50 lbs)", 
      "image": "https://example.com/images/fitness2.jpg", 
      "price": 79.99, 
      "rating": 4.7 
    },
    { "id": 43,
      "category": "fitness", 
      "name": "Resistance Bands", 
      "image": "https://example.com/images/fitness3.jpg", 
      "price": 14.99, 
      "rating": 4.5 
    },
    { "id": 44,
      "category": "fitness", 
      "name": "Adjustable Kettlebell", 
      "image": "https://example.com/images/fitness4.jpg", 
      "price": 49.99, 
      "rating": 4.6 
    },
    { "id": 45,
      "category": "fitness", 
      "name": "Fitness Tracker Watch", 
      "image": "https://example.com/images/fitness5.jpg", 
      "price": 59.99, 
      "rating": 4.7 
    },
    { "id": 46,
      "category": "fitness", 
      "name": "Jump Rope", 
      "image": "https://example.com/images/fitness6.jpg", 
      "price": 9.99, 
      "rating": 4.3 
    },
    { "id": 47,
      "category": "fitness", 
      "name": "Foam Roller", 
      "image": "https://example.com/images/fitness7.jpg", 
      "price": 24.99, 
      "rating": 4.6 
    },
    { "id": 48,
      "category": "fitness", 
      "name": "Pull-up Bar", 
      "image": "https://example.com/images/fitness8.jpg", 
      "price": 39.99, 
      "rating": 4.5 
    },
    { "id": 49,
      "category": "fitness", 
      "name": "Exercise Ball", 
      "image": "https://example.com/images/fitness9.jpg", 
      "price": 29.99, 
      "rating": 4.4 
    },
    { "id": 50,
      "category": "fitness", 
      "name": "Cycling Gloves", 
      "image": "https://example.com/images/fitness10.jpg", 
      "price": 14.99, 
      "rating": 4.2 
    }
  



  ]


//     {
//     id:1,
//     category:"electrinics",
//     name:"Charger",
//     image:"",
//     price:2,
//     rating:4.9,

// }


  // Electronics (10)
 

export default DataApi