const DataApi=[
    { "id": 1,
      "category": "electronics", 
      "name": "Portable Charger", 
      "image": "https://images.pexels.com/photos/3921703/pexels-photo-3921703.jpeg", 
      "price": 19.99, 
      "rating": 4.8 
    },
    { "id": 2,
      "category": "electronics", 
      "name": "Wireless Earbuds", 
      "image": "https://images.pexels.com/photos/9130517/pexels-photo-9130517.jpeg", 
      "price": 39.99, 
      "rating": 4.6 
    },
    { "id": 3,
      "category": "electronics", 
      "name": "Bluetooth Speaker", 
      "image": "https://images.unsplash.com/photo-1589256469067-ea99122bbdc4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Qmx1ZXRvb3RoJTIwU3BlYWtlcnxlbnwwfDB8MHx8fDA%3D", 
      "price": 29.99, 
      "rating": 4.5 
    },
    { "id": 4,
      "category": "electronics", 
      "name": "Smart Watch", 
      "image": "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=1172&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", 
      "price": 69.99, 
      "rating": 4.4 
    },
    { "id": 5,
      "category": "electronics", 
      "name": "Webcam", 
      "image": "https://images.unsplash.com/photo-1670278458296-00ff8a63141e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fFdlYmNhbXxlbnwwfDB8MHx8fDA%3D", 
      "price": 49.99, 
      "rating": 4.3 
    },
    { "id": 6,
      "category": "electronics", 
      "name": "USB-C Hub", 
      "image": "https://plugable.com/cdn/shop/files/main_ori_300f17f1-f716-4875-8102-d6011170109c.jpg?v=1752510846", 
      "price": 24.99, 
      "rating": 4.2 
    },
    { "id": 7,
      "category": "electronics", 
      "name": "LED Light Strip", 
      "image": "https://m.media-amazon.com/images/I/61rbCAFvHvL._UF894,1000_QL80_.jpg", 
      "price": 14.99, 
      "rating": 4.4 
    },
    { "id": 8,
      "category": "electronics", 
      "name": "VR Headset", 
      "image": "https://assets.arpost.co/wp-content/uploads/2018/01/28221042/oculus-go-1-e1516017131531.jpg", 
      "price": 109.99, 
      "rating": 4.1 
    },
    { "id": 9,
      "category": "electronics", 
      "name": "Portable Projector", 
      "image": "https://m.media-amazon.com/images/I/51CnRBSVnrL.jpg", 
      "price": 199.99, 
      "rating": 4.3 
    },
    { "id": 10,
      "category": "electronics", 
      "name": "External SSD", 
      "image": "https://plugable.com/cdn/shop/products/main_ori_c1020fbb-3cb4-4622-8838-fb32b49f0027_grande.jpg?v=1645555703", 
      "price": 89.99, 
      "rating": 4.6 
    },

    { "id": 11,
      "category": "fashion", 
      "name": "Crew Neck T‑Shirt", 
      "image": "https://ashanderie.com/cdn/shop/files/short-sleeve-premium-tee-white-pima-cotton-crew-neck-tee-43120910237994.jpg?v=1754420771&width=2160", 
      "price": 19.99, 
      "rating": 4.5 
    },
    { "id": 12,
      "category": "fashion", 
      "name": "Slim-fit Jeans", 
      "image": "https://in.benetton.com/cdn/shop/files/Benetton_24AI_24A4REJE9098I_901_F_1fc5ae90-aa4f-4b85-81cf-ae3f4fb6cca3.jpg?v=1723281522", 
      "price": 49.99, 
      "rating": 4.4 
    },
    { "id": 13,
      "category": "fashion", 
      "name": "Canvas Sneakers", 
      "image": "https://m.media-amazon.com/images/I/71KRqfm5iAL._UY900_.jpg", 
      "price": 59.99, 
      "rating": 4.6 
    },
    { "id": 14,
      "category": "fashion", 
      "name": "Leather Belt", 
      "image": "https://i.etsystatic.com/31569917/r/il/5bad10/4746038704/il_570xN.4746038704_o12h.jpg", 
      "price": 24.99, 
      "rating": 4.3 
    },
    { "id": 15,
      "category": "fashion", 
      "name": "Sunglasses (Aviator)", 
      "image": "https://assets2.sunglasshut.com/cdn-record-files-pi/c07af352-2afe-408f-b4b1-abc2018648ee/47d8f7e0-83e8-4511-9d8f-acb40125377c/0RB3025__002_48__STD__shad__qt.png", 
      "price": 29.99, 
      "rating": 4.4 
    },
    { "id": 16,
      "category": "fashion", 
      "name": "Wool Scarf", 
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs9veNXnRPIklfuAlojzl3ZZYqECagOP2nFAK6PJ2Do5yrRXgwM7cIMtctgiHbWnwpp1w&usqp=CAU", 
      "price": 22.99, 
      "rating": 4.2 
    },
    { "id": 17,
      "category": "fashion", 
      "name": "Denim Jacket", 
      "image": "https://www.apetogentleman.com/wp-content/uploads/2020/03/wear-denim-jacket-2.jpg", 
      "price": 79.99, 
      "rating": 4.5 
    },
    { "id": 18,
      "category": "fashion", 
      "name": "Chelsea Boots", 
      "image": "https://www.loding.fr/cdn/shop/products/CHA367BK_1_2048x.jpg?v=1670522255", 
      "price": 99.99, 
      "rating": 4.7 
    },
    { "id": 19,
      "category": "fashion", 
      "name": "Baseball Cap", 
      "image": "https://www.neweracap.co.za/cdn/shop/files/12572843_3d86767f-ea74-4bfa-99e4-ff2046f0b3bf.jpg?v=1698055029", 
      "price": 14.99, 
      "rating": 4.1 
    },
    { "id": 20,
      "category": "fashion", 
      "name": "Canvas Backpack", 
      "image": "https://www.westernleathergoods.com/cdn/shop/files/Green-Waxed-Canvas-Leather-Backpack_1400x.jpg?v=1689751772", 
      "price": 44.99, 
      "rating": 4.6 
    },

    { "id": 21,
      "category": "home", 
      "name": "Air Fryer", 
      "image": "", 
      "price": 89.99, 
      "rating": 4.5 
    },
    { "id": 22,
      "category": "home", 
      "name": "Robot Vacuum", 
      "image": "https://example.com/images/home2.jpg", 
      "price": 249.99, 
      "rating": 4.3 
    },
    { "id": 23,
      "category": "home", 
      "name": "LED Table Lamp", 
      "image": "https://example.com/images/home3.jpg", 
      "price": 29.99, 
      "rating": 4.4 
    },
    { "id": 24,
      "category": "home", 
      "name": "Decorative Rug", 
      "image": "https://example.com/images/home4.jpg", 
      "price": 59.99, 
      "rating": 4.2 
    },
    { "id": 25,
      "category": "home", 
      "name": "Wall Art Print", 
      "image": "https://example.com/images/home5.jpg", 
      "price": 39.99, 
      "rating": 4.5 
    },
    { "id": 26,
      "category": "home", 
      "name": "Bookshelf", 
      "image": "https://example.com/images/home6.jpg", 
      "price": 129.99, 
      "rating": 4.3 
    },
    { "id": 27,
      "category": "home", 
      "name": "Dining Table (Wooden)", 
      "image": "https://example.com/images/home7.jpg", 
      "price": 299.99, 
      "rating": 4.6 
    },
    { "id": 28,
      "category": "home", 
      "name": "Curtain Panels", 
      "image": "https://example.com/images/home8.jpg", 
      "price": 49.99, 
      "rating": 4.1 
    },
    { "id": 29,
      "category": "home", 
      "name": "Floor Mirror", 
      "image": "https://example.com/images/home9.jpg", 
      "price": 89.99, 
      "rating": 4.4 
    },
    { "id": 30,
      "category": "home", 
      "name": "Storage Bins (Set of 3)", 
      "image": "https://example.com/images/home10.jpg", 
      "price": 34.99, 
      "rating": 4.2 
    },
    { "id": 31,
      "category": "books", 
      "name": "The Great Gatsby", 
      "image": "https://example.com/images/books1.jpg", 
      "price": 9.99, 
      "rating": 4.7 
    },
    { "id": 32,
      "category": "books", 
      "name": "1984 by George Orwell", 
      "image": "https://example.com/images/books2.jpg", 
      "price": 8.99, 
      "rating": 4.8 
    },
    { "id": 33,
      "category": "books", 
      "name": "To Kill a Mockingbird", 
      "image": "https://example.com/images/books3.jpg", 
      "price": 7.99, 
      "rating": 4.9 
    },
    { "id": 34,
      "category": "books", 
      "name": "The Hobbit", 
      "image": "https://example.com/images/books4.jpg", 
      "price": 10.99, 
      "rating": 4.8 
    },
    { "id": 35,
      "category": "books", 
      "name": "Sapiens: A Brief History of Humankind", 
      "image": "https://example.com/images/books5.jpg", 
      "price": 14.99, 
      "rating": 4.7 
    },
    { "id": 36,
      "category": "books", 
      "name": "The Catcher in the Rye", 
      "image": "https://example.com/images/books6.jpg", 
      "price": 9.49, 
      "rating": 4.2 
    },
    { "id": 37,
      "category": "books", 
      "name": "Harry Potter and the Sorcerer's Stone", 
      "image": "https://example.com/images/books7.jpg", 
      "price": 12.99, 
      "rating": 4.9 
    },
    { "id": 38,
      "category": "books", 
      "name": "Pride and Prejudice", 
      "image": "https://example.com/images/books8.jpg", 
      "price": 8.49, 
      "rating": 4.6 
    },
    { "id": 39,
      "category": "books", 
      "name": "Meditations by Marcus Aurelius", 
      "image": "https://example.com/images/books9.jpg", 
      "price": 6.99, 
      "rating": 4.8 
    },
    { "id": 40,
      "category": "books", 
      "name": "Atomic Habits", 
      "image": "https://example.com/images/books10.jpg", 
      "price": 11.99, 
      "rating": 4.7 
    },

    { "id": 41,
      "category": "fitness", 
      "name": "Yoga Mat", 
      "image": "https://example.com/images/fitness1.jpg", 
      "price": 19.99, 
      "rating": 4.8 
    },
    { "id": 42,
      "category": "fitness", 
      "name": "Dumbbell Set (10-50 lbs)", 
      "image": "https://example.com/images/fitness2.jpg", 
      "price": 79.99, 
      "rating": 4.7 
    },
    { "id": 43,
      "category": "fitness", 
      "name": "Resistance Bands", 
      "image": "https://example.com/images/fitness3.jpg", 
      "price": 14.99, 
      "rating": 4.5 
    },
    { "id": 44,
      "category": "fitness", 
      "name": "Adjustable Kettlebell", 
      "image": "https://example.com/images/fitness4.jpg", 
      "price": 49.99, 
      "rating": 4.6 
    },
    { "id": 45,
      "category": "fitness", 
      "name": "Fitness Tracker Watch", 
      "image": "https://example.com/images/fitness5.jpg", 
      "price": 59.99, 
      "rating": 4.7 
    },
    { "id": 46,
      "category": "fitness", 
      "name": "Jump Rope", 
      "image": "https://example.com/images/fitness6.jpg", 
      "price": 9.99, 
      "rating": 4.3 
    },
    { "id": 47,
      "category": "fitness", 
      "name": "Foam Roller", 
      "image": "https://example.com/images/fitness7.jpg", 
      "price": 24.99, 
      "rating": 4.6 
    },
    { "id": 48,
      "category": "fitness", 
      "name": "Pull-up Bar", 
      "image": "https://example.com/images/fitness8.jpg", 
      "price": 39.99, 
      "rating": 4.5 
    },
    { "id": 49,
      "category": "fitness", 
      "name": "Exercise Ball", 
      "image": "https://example.com/images/fitness9.jpg", 
      "price": 29.99, 
      "rating": 4.4 
    },
    { "id": 50,
      "category": "fitness", 
      "name": "Cycling Gloves", 
      "image": "https://example.com/images/fitness10.jpg", 
      "price": 14.99, 
      "rating": 4.2 
    }
  



  ]


//     {
//     id:1,
//     category:"electrinics",
//     name:"Charger",
//     image:"",
//     price:2,
//     rating:4.9,

// }


  // Electronics (10)
 

export default DataApi