const apis=
    [
  // --- Electronics (already 20) ---
  { id: 1, category: "electronics", name: "Charger", image: "", price: 2, rating: 4.9 },
  { id: 2, category: "electronics", name: "Power Bank", image: "", price: 15, rating: 4.7 },
  { id: 3, category: "electronics", name: "Bluetooth Speaker", image: "", price: 25, rating: 4.5 },
  { id: 4, category: "electronics", name: "Wireless Earbuds", image: "", price: 35, rating: 4.8 },
  { id: 5, category: "electronics", name: "Smart Watch", image: "", price: 55, rating: 4.6 },
  { id: 6, category: "electronics", name: "USB Cable", image: "", price: 3, rating: 4.4 },
  { id: 7, category: "electronics", name: "Phone Holder", image: "", price: 7, rating: 4.3 },
  { id: 8, category: "electronics", name: "Laptop Stand", image: "", price: 20, rating: 4.6 },
  { id: 9, category: "electronics", name: "Webcam", image: "", price: 30, rating: 4.5 },
  { id: 10, category: "electronics", name: "Keyboard", image: "", price: 25, rating: 4.7 },
  { id: 11, category: "electronics", name: "Mouse", image: "", price: 10, rating: 4.2 },
  { id: 12, category: "electronics", name: "Monitor", image: "", price: 120, rating: 4.8 },
  { id: 13, category: "electronics", name: "Router", image: "", price: 45, rating: 4.3 },
  { id: 14, category: "electronics", name: "Tablet", image: "", price: 150, rating: 4.5 },
  { id: 15, category: "electronics", name: "Smart TV", image: "", price: 300, rating: 4.7 },
  { id: 16, category: "electronics", name: "Drone", image: "", price: 80, rating: 4.4 },
  { id: 17, category: "electronics", name: "VR Headset", image: "", price: 90, rating: 4.6 },
  { id: 18, category: "electronics", name: "LED Light Strip", image: "", price: 12, rating: 4.4 },
  { id: 19, category: "electronics", name: "External Hard Drive", image: "", price: 60, rating: 4.5 },
  { id: 20, category: "electronics", name: "Portable Projector", image: "", price: 100, rating: 4.6 },

  // --- Fashion (already 20) ---
  { id: 21, category: "fashion", name: "T-Shirt", image: "", price: 10, rating: 4.5 },
  { id: 22, category: "fashion", name: "Jeans", image: "", price: 30, rating: 4.4 },
  { id: 23, category: "fashion", name: "Sneakers", image: "", price: 50, rating: 4.7 },
  { id: 24, category: "fashion", name: "Jacket", image: "", price: 60, rating: 4.6 },
  { id: 25, category: "fashion", name: "Watch", image: "", price: 45, rating: 4.5 },
  { id: 26, category: "fashion", name: "Sunglasses", image: "", price: 15, rating: 4.3 },
  { id: 27, category: "fashion", name: "Scarf", image: "", price: 8, rating: 4.2 },
  { id: 28, category: "fashion", name: "Backpack", image: "", price: 35, rating: 4.6 },
  { id: 29, category: "fashion", name: "Hat", image: "", price: 12, rating: 4.4 },
  { id: 30, category: "fashion", name: "Gloves", image: "", price: 9, rating: 4.1 },
  { id: 31, category: "fashion", name: "Belt", image: "", price: 11, rating: 4.3 },
  { id: 32, category: "fashion", name: "Dress", image: "", price: 40, rating: 4.5 },
  { id: 33, category: "fashion", name: "Shorts", image: "", price: 18, rating: 4.4 },
  { id: 34, category: "fashion", name: "Hoodie", image: "", price: 25, rating: 4.6 },
  { id: 35, category: "fashion", name: "Socks", image: "", price: 5, rating: 4.0 },
  { id: 36, category: "fashion", name: "Tank Top", image: "", price: 8, rating: 4.2 },
  { id: 37, category: "fashion", name: "Leather Shoes", image: "", price: 70, rating: 4.5 },
  { id: 38, category: "fashion", name: "Cap", image: "", price: 7, rating: 4.1 },
  { id: 39, category: "fashion", name: "Raincoat", image: "", price: 28, rating: 4.3 },
  { id: 40, category: "fashion", name: "Skirt", image: "", price: 22, rating: 4.4 },

  // --- Home (20) ---
  { id: 41, category: "home", name: "Air Fryer", image: "", price: 60, rating: 4.5 },
  { id: 42, category: "home", name: "Blender", image: "", price: 45, rating: 4.4 },
  { id: 43, category: "home", name: "Vacuum Cleaner", image: "", price: 110, rating: 4.6 },
  { id: 44, category: "home", name: "Wall Clock", image: "", price: 20, rating: 4.2 },
  { id: 45, category: "home", name: "Curtains", image: "", price: 30, rating: 4.1 },
  { id: 46, category: "home", name: "Cushion", image: "", price: 15, rating: 4.3 },
  { id: 47, category: "home", name: "Table Lamp", image: "", price: 25, rating: 4.5 },
  { id: 48, category: "home", name: "Cutlery Set", image: "", price: 35, rating: 4.6 },
  { id: 49, category: "home", name: "Dining Table", image: "", price: 200, rating: 4.7 },
  { id: 50, category: "home", name: "Mirror", image: "", price: 40, rating: 4.3 },
  { id: 51, category: "home", name: "Storage Box", image: "", price: 18, rating: 4.2 },
  { id: 52, category: "home", name: "Desk Organizer", image: "", price: 12, rating: 4.4 },
  { id: 53, category: "home", name: "Coasters", image: "", price: 10, rating: 4.1 },
  { id: 54, category: "home", name: "Wall Art", image: "", price: 30, rating: 4.5 },
  { id: 55, category: "home", name: "Bookshelf", image: "", price: 75, rating: 4.6 },
  { id: 56, category: "home", name: "Doormat", image: "", price: 9, rating: 4.2 },
  { id: 57, category: "home", name: "Coffee Table", image: "", price: 4.2}

]